server:
  port: 8099
spring:
  data:
    hbase:
      quorum: localhost
      node-parent: /hbase
      zk-client-port: 2181
      root-dir: /hbase
      client-properties: hbase.client.retries.number=3
